version: "3.9"
services:
  cassandra:
    image: cassandra:3.11.4
    expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
  cassandra-web:
    image: markusgulden/cassandra-web
    depends_on:
    - cassandra
    environment:
      CASSANDRA_HOST_IPS: localhost
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
    - 3000:3000
